### ISSUE TITLE
API resource without hosts field doesn't work

### ISSUE THREAD

**Issue by markgandy** [localz/terraform-provider-kong#3]
If you create an API resource that matches on `uris` but not `hosts`, it doesn't work. If `hosts` field is not provided in `kong_api` resource, it creates the API with `hosts = {}`. This then tries to match using `hosts` as well, and so doesn't work as expected.

When you create via admin API directly it works as expected (if `hosts` not in payload then API is created without `hosts` field)

**Comment by markgandy** [comment]
Actually, looks like this is because `strip_uri` is always set to `true`

**Comment by hugomd** [comment]
Closed by ee36ec379e1196ee1d4d06b5fb2974679bbe9312
